name: islam_app
description: "IslamApp V 1.0 - Advanced Financial System"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # الربط مع الـ API
  http: ^1.1.0

  # حفظ البيانات محلياً (تذكرني)
  shared_preferences: ^2.2.2

  # فتح الروابط الخارجية
  url_launcher: ^6.2.1

  # الوقت والتاريخ والعملات
  intl: ^0.19.0

  # الرسوم البيانية للتقارير
  fl_chart: ^0.66.0

  cupertino_icons: ^1.0.6

  # فيربيز
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1

  # التعامل مع الإكسيل والملفات
  excel: ^4.0.3
  path_provider: ^2.1.2
  open_file: ^3.3.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

  # مكتبة الأيقونات
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # تعريف الأصول (الصور والأيقونات)
  # تأكد أن المجلدات موجودة فعلياً في مشروعك بنفس الأسماء
  assets:
    - assets/images/
    - assets/images/app_icon.png

  # # تعريف خط Cairo
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700

# إعدادات أيقونة البرنامج
flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#020617"
    theme_color: "#020617"
  android: true
  ios: true