name: Deploy Flutter Web
on:
  push:
    branches:
      - main # أو اسم البرانش بتاعك

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore Firebase Options
        run: |
          # بنأكد عليه يدخل فولدر الـ frontend لو مش موجود جواه
          mkdir -p frontend/lib 
          echo "${{ secrets.FIREBASE_OPTIONS_B64 }}" | base64 --decode > frontend/lib/firebase_options.dart

      - name: Build Web
        working-directory: frontend # مهم جداً عشان الأوامر تتنفذ في مكانها الصح
        run: |
          flutter pub get
          flutter build web --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages