name: Sync Full Project to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # clone space
          git clone https://Islamadel:$HF_TOKEN@huggingface.co/spaces/Islamadel/islam-app-api hf-space

          # امسح محتوى الـ space
          rm -rf hf-space/*

          # انسخ كل المشروع ما عدا hf-space نفسه
          rsync -av --progress ./ ./hf-space \
            --exclude hf-space \
            --exclude .git
            --exclude "frontend/assets/images/app_icon.png"
            --exclude "frontend/web/icons/Icon-512.png"
            --exclude "frontend\web\favicon.png"
            --exclude "frontend\web\icons\Icon-maskable-512.png"

          cd hf-space

          rm -rf .git
          git init

          git remote add origin https://Islamadel:$HF_TOKEN@huggingface.co/spaces/Islamadel/islam-app-api

          git add .

          git commit -m "Auto sync full project" || echo "No changes"

          git branch -M main

          git push -f origin main