name: Sync Full Project to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # عشان يجيب التاريخ كامل لو محتاجه

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 1. عمل Clone للـ Space
          git clone https://Islamadel:$HF_TOKEN@huggingface.co/spaces/Islamadel/islam-app-api hf-space

          # 2. مسح محتوى الـ space القديم (ما عدا فولدر .git الخاص بهيوجينج)
          find hf-space -maxdepth 1 ! -name '.git' ! -name 'hf-space' -exec rm -rf {} +

          # 3. نسخ المشروع مع استبعاد ملفات الصور المسببة للمشكلة
          # أضفنا --exclude للمسارات اللي هيوجينج بيرفضها
          rsync -av --progress ./ ./hf-space \
            --exclude hf-space \
            --exclude .git \
            --exclude ".github" \
            --exclude "frontend/assets/images/app_icon.png" \
            --exclude "frontend/web/icons/Icon-512.png"
            --exclude "frontend\web\favicon.png"
            --exclude "frontend\web\icons\Icon-maskable-512.png"
          cd hf-space

          # 4. رفع التعديلات (هنا بنستخدم الـ .git بتاع هيوجينج الأصلي اللي نزل مع الـ clone)
          # لو حابب تكمل بطريقتك (git init) مفيش مشكلة بس الطريقة دي أضمن
          git add .
          git commit -m "Auto sync: skipping binary files" || echo "No changes"
          
          # الرفع بقوة لضمان تحديث الـ main هناك
          git push -f origin main